---
title: "Final Project"
author: "Yihong Hu & Shujing Yi"
date: "4/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(tidycensus)
library(tidyverse)
library(ggplot2)
library(mapview)
library(lubridate)
library(RSocrata)
library(mapview)
library(ggcorrplot)
library(viridis)
library(extrafont)

census_api_key("94efffd19b56ad527e379faea1653ee74dc3de4a",overwrite = TRUE)

theme_map <- function(...) {
  theme_minimal() +
  theme(
    text = element_text(family = "Poppins", color = "#22211d"),
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "#f5f5f2", color = NA), 
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.border = element_blank(),
    ...
  )
}

```

# Introduction

# Data Wrangling

```{r cars}

#Philly Street Light Poles
Street_Poles_Data <- st_read("https://opendata.arcgis.com/datasets/9059a7546b6a4d658bef9ce9c84e4b03_0.geojson") 

Street_Poles_Lumen <- Street_Poles_Data %>% select(LUM_SIZE) %>% na.omit() %>% st_transform(crs = 4326)

# Philly Block Group Census
Philly_Census <- get_acs(geography = "block group",
                         state = 42,
                         county = 101,
                         year = 2020,
                         geometry = TRUE,
                         output="wide",
                         variable =(c(Pop = "B19013_001",
                                      PopBelow5M = "B01001_003",
                                      Pop_5_9M = "B01001_004",
                                      PopBeloq5F = "B01001_027",
                                      Pop_5_9F = "B01001_028")))

Philly_Pop_Above60 <- get_acs(geography = "block group",
                         state = 42,
                         county = 101,
                         year = 2020,
                         geometry = TRUE,
                         output = "wide",
                         variable =(c("B01001_018"	,
                                      "B01001_019"	,
                                      "B01001_020"	,
                                      "B01001_021"	,
                                      "B01001_022"	,
                                      "B01001_023"	,
                                      "B01001_024"	,
                                      "B01001_025",
                                      "B01001_042"	,
                                      "B01001_043"	,
                                      "B01001_044"	,
                                      "B01001_045"	,
                                      "B01001_046"	,
                                      "B01001_047"	,
                                      "B01001_048"	,
                                      "B01001_049"	)))

Philly_commute <- get_acs(geography = "tract",
                         state = 42,
                         county = 101,
                         output = "wide",
                         year = 2020,
                         geometry = TRUE,
                         variable =(c(Bike	=	"B08006_014"	,
                                      Walk	=	"B08006_015"	,
                                      Public_Trans	=	"B08006_008")))

Philly_Race <- read.csv("2020Census.csv")
Philly_Race$GEO_ID<-gsub("1500000US","",as.character(Philly_Race$GEO_ID))

Report_311_2020 <-
  read.csv("public_cases_2020.csv")%>%
  filter(service_name=="Street Light Outage")

Report_311_2019 <-
  read.csv("public_cases_2019.csv") %>%
  filter(service_name=="Street Light Outage")

Report_311_2018 <-
  read.csv("public_cases_fc_2018.csv") %>%
  filter(service_name=="Street Light Outage")

Report_311_2017 <-
  read.csv("public_cases_fc_2017.csv") %>%
  filter(service_name=="Street Light Outage")

Report_311_2016 <-
  read.csv("public_cases_fc_2016.csv") %>%
  filter(service_name=="Street Light Outage")

Report_light_out_full <-
  rbind(Report_311_2018,Report_311_2019,Report_311_2020,Report_311_2017,Report_311_2016)%>%na.omit %>%
  st_as_sf(coords = c("lon","lat"),crs = 4326) %>%
  distinct(updated_datetime, .keep_all = T) 

#Open Case with lumen
Report_light_out_open <-
  Report_light_out_full %>%
  filter(status == "Open")

# Crash Data between 2018 - 2020
Crash <-
  st_read("https://opendata.arcgis.com/api/v3/datasets/e703eb63ec484aa6beae1268372efa53_0/downloads/data?format=geojson&spatialRefId=4326")

head(Crash)

Crash_Ped <-
  Crash %>%
  filter(PED_COUNT > 0)

Crash_Ped$HOUR_OF_DA <- as.character(Crash_Ped$HOUR_OF_DA)

# Hour of crashes

Crash_Ped %>%
  mutate(HOUR_DA_FACTOR = factor(HOUR_OF_DA, levels = c(as.character(seq(0,24)))))%>%
  group_by(HOUR_DA_FACTOR)%>%
  tally()%>%
  group_by(HOUR_DA_FACTOR)%>%
  summarise(SUM_HOUR = sum(n)) %>%
  filter(!HOUR_DA_FACTOR == "99")%>%
ggplot(aes(HOUR_DA_FACTOR, SUM_HOUR, fill=HOUR_DA_FACTOR)) + 
         geom_bar(position = "dodge", stat = "summary", fun.y = "mean")+ xlab("Hour of the day") + ylab("Total Crash") + labs(title = "Pedestrian crashes by hours between 2016 - 2020")+ theme_minimal()

```

```{r catagorical}
#Pedestrian crashes by time of the day
Crash_Ped$HOUR_OF_DA <- as.numeric(Crash_Ped$HOUR_OF_DA)

Crash_Ped_PennDot_sum <-
  Crash_Ped %>%
  mutate(TIME_OF_DAY = case_when(HOUR_OF_DA < 7 | HOUR_OF_DA > 18 ~ "Overnight",
                                 HOUR_OF_DA >= 7 & HOUR_OF_DA < 10 ~ "AM Rush",
                                 HOUR_OF_DA >= 10 & HOUR_OF_DA < 15 ~ "Mid-Day",
                                 HOUR_OF_DA >= 15 & HOUR_OF_DA <= 18 ~ "PM Rush"))%>%
  group_by(HOUR_OF_DA, TIME_OF_DAY) %>%
  tally() %>%
  group_by(TIME_OF_DAY) %>%
  summarise(sum_crash = sum(n))%>%
  mutate(pct_crash = sum_crash/sum(sum_crash)*100)

Crash_Ped_PennDot_sum %>%
  ggplot(aes(TIME_OF_DAY, sum_crash, fill = TIME_OF_DAY))+
  geom_bar(position = "dodge", stat = "summary", fun.y = "mean") + xlab("Time of the day")+ylab("Total Crash Counts") + labs(title = "Pedestrian Crashes by Time of the Day") + theme_minimal()

```

```{r}

#Fatal Pedestrian Crashes by time of the day

Crash_Ped_PennDot_Fatal <-
  Crash_Ped %>%
  filter(FATAL_COUN > 0)

Crash_Ped_PennDot_Fatal_sum <-
Crash_Ped_PennDot_Fatal %>%
  mutate(TIME_OF_DAY = case_when(HOUR_OF_DA < 7 | HOUR_OF_DA > 18 ~ "Overnight",
                                 HOUR_OF_DA >= 7 & HOUR_OF_DA < 10 ~ "AM Rush",
                                 HOUR_OF_DA >= 10 & HOUR_OF_DA < 15 ~ "Mid-Day",
                                 HOUR_OF_DA >= 15 & HOUR_OF_DA <= 18 ~ "PM Rush"))%>%
  group_by(HOUR_OF_DA, TIME_OF_DAY) %>%
  tally() %>%
  group_by(TIME_OF_DAY) %>%
  summarise(sum_crash = sum(n))%>%
  mutate(pct_crash = sum_crash/sum(sum_crash)*100)

Crash_Ped_PennDot_Fatal_sum %>%
  ggplot(aes(TIME_OF_DAY, sum_crash, fill = TIME_OF_DAY))+
  geom_bar(position = "dodge", stat = "summary", fun.y = "mean") + xlab("Time of the day")+ylab("Total Crash Counts") + labs(title = "Fatal Pedestrian Crashes by Time of the Day")+theme_minimal()

```

```{r}
Crash_Fatal_PennDot <-
  Crash%>%
  filter(FATAL_COUN > 0)

Fatal_Crash <-
  st_read("https://opendata.arcgis.com/datasets/6510bfe4d500460caef528511d084335_0.geojson")

Fatal_Crash2 <-
  Fatal_Crash %>%
  mutate(interval60 = floor_date(ymd_hms(DATE_), unit = "hour"))

```

```{r}

#Mapping out Lumens in Philly
p <- ggplot()+
  geom_sf(data = Philly_Census,color = "grey30")+
  geom_sf(data = Street_Poles_Lumen, aes(color = LUM_SIZE),alpha=0.5) +  labs(x = NULL, 
         y = NULL, 
         title = "Light Brightness by Lumen in Philadelphia", 
         caption = "Open Data Philly",
          color = "Lumens")

p + scale_color_viridis_b()+theme_map()

#Mapping out dis-functioning lights

lum_0 <-
  Street_Poles_Lumen %>%
  filter(LUM_SIZE == 0) 

lum_0_geo <-
  lum_0 %>%
  select(geometry)

disfunction_light_geo <-
  Report_light_out_open %>%
  select(geometry) %>%
  rbind(.,lum_0_geo)

ggplot()+
  geom_sf(data = Philly_Census,color = "grey30")+
  geom_sf(data = Street_Poles_Lumen,color = "seagreen",alpha=0.8) +  
  geom_sf(data = disfunction_light_geo,color = "red", alpha = 0.5 ) +
  labs(x = NULL, 
         y = NULL, 
         title = "Disfunctioning light in Philly", 
         caption = "Open Data Philly",
          color = "Lumens")

```

```{r}
#fishnet
Philly_boundary <-
  st_read("https://opendata.arcgis.com/datasets/405ec3da942d4e20869d4e1449a2be48_0.geojson")%>%
  st_transform('ESRI:102271')

fishnet <- 
  st_make_grid(Philly_boundary,
               cellsize = 500, 
               square = TRUE) %>%
  .[Philly_boundary] %>%            
  st_sf() %>%
  mutate(uniqueID = rownames(.))%>%
  st_transform(crs = 4326)

#Light in Fishnet
light_net <- 
  Street_Poles_Lumen %>%
  st_transform(crs = 4326)%>%
  filter(!LUM_SIZE == 0)%>%
  select(-LUM_SIZE) %>%
  mutate(countLight = 1) %>% 
  aggregate(., fishnet, sum) %>%
  mutate(countLight = replace_na(countLight, 0),
         uniqueID = rownames(.),
         cvID = sample(round(nrow(fishnet) / 24), 
                       size=nrow(fishnet), replace = TRUE))

#Light Count in each fishnet cell
ggplot() +
  geom_sf(data = light_net, aes(fill = countLight), color = NA) +
  scale_fill_viridis_b() +
  labs(title = "Street Light Pole Count in each Fishnet Cell", Legend = "Street Pole Count", caption="Fig.2") +
  theme_map()

```

```{r data cleaning}

Agg_age_below_10_f <-
  Philly_Census %>%
  mutate(Age_below_10 = PopBelow5ME + Pop_5_9ME + PopBeloq5FE +Pop_5_9FE)%>%
  select(-ends_with("M"),-ends_with("E"))%>%
  st_transform(crs = 4326)%>%
  mutate(Legend = "Below10") %>%
  rename(Count = Age_below_10)%>%
  select(GEOID,Count,Legend) %>%
  st_centroid() %>%
  st_join(.,fishnet)%>%
  group_by(uniqueID) %>%
  summarize(CountBelow10 = sum(Count))

fishnet1 <-
  Agg_age_below_10_f %>%
  st_drop_geometry()%>%
  left_join(fishnet)%>%
  st_as_sf

Agg_above_60 <-
  Philly_Pop_Above60 %>%
  mutate(Age_Above60 = B01001_018E + B01001_019E +
                                      B01001_020E+                
                                      B01001_021E +
                                      B01001_022E +
                                      B01001_023E+
                                      B01001_024E+
                                      B01001_025E+
                                      B01001_042E+
                                      B01001_043E+
                                      B01001_044E+
                                      B01001_045E+
                                      B01001_046E+
                                      B01001_047E+
                                      B01001_048E+
                                      B01001_049E)%>%
  select(GEOID,geometry,Age_Above60) %>%
  st_transform(crs = 4326)%>%
  mutate(Legend = "Above60") %>%
  rename(Count = Age_Above60)%>%
  select(GEOID,Count,Legend) %>%
  st_centroid()%>%
   st_join(.,fishnet)%>%
  group_by(uniqueID) %>%
  summarize(CountAbove60 = sum(Count))

fishnet2 <-
  Agg_above_60 %>%
  st_drop_geometry()%>%
  left_join(fishnet)%>%
  st_as_sf()

No_car_commute <- 
  Philly_commute %>%
  mutate(Non_auto_commute = BikeE, Public_TransE, WalkE) %>%
  select(geometry, Non_auto_commute, GEOID) %>%
  st_transform(crs = 4326) %>%
  mutate(Legend = "NoCar") %>%
  rename(Count = Non_auto_commute)%>%
  select(GEOID,Count,Legend) %>%
  st_centroid()%>%
   st_join(.,fishnet)%>%
  group_by(uniqueID) %>%
  summarize(CountNoCar = sum(Count))

fishnet3 <-
No_car_commute %>% 
  st_drop_geometry()%>%
  left_join(fishnet)%>%
  st_as_sf()
  

#Crash Count in each block Group

Crash_geo <-
Crash_Ped %>%
  select(geometry) %>%
  st_transform(crs = 4326)%>%
  mutate(CrashCount = 1)%>%
  st_join(.,fishnet)%>%
  group_by(uniqueID) %>%
  summarize(CrashCount = sum(CrashCount))

fishnet4 <-
  Crash_geo %>% 
  st_drop_geometry()%>%
  left_join(fishnet)%>%
  st_as_sf()

ggplot()+
  geom_sf(data = Philly_boundary)+
  geom_sf(data = fishnet4, aes(fill = CrashCount))+
  scale_fill_viridis(option = "B", direction = -1)

```

```{r Tree}
Tree <-
read.csv("PPR_Tree_Inventory_2021.csv")%>%
  st_as_sf(coords = c("LOC_X","LOC_Y"),crs = 4326) %>%
  st_transform(crs = 4326)%>%
  mutate(TreeCount = 1)

fishnet_5 <-
  Tree %>%
  st_join(.,fishnet)%>%
  group_by(uniqueID) %>%
  summarize(CountTree = sum(TreeCount))%>% st_drop_geometry()%>%
  left_join(fishnet)%>%
  st_as_sf()

  

Tree_geoid2 <-
  Tree_geoid %>%
  st_drop_geometry()%>%
  mutate(Legend = "Tree")%>%
  rename(Count = TreeCount)%>%
  select(GEOID,Count,Legend)

```

```{r}
block_geo <-
  Philly_Census %>%
  select(geometry,GEOID)

Philly_Race <-
Philly_Race %>%
  rename(GEOID=GEO_ID)%>%
  left_join(block_geo)%>%
  st_as_sf()
  
Philly_Race <-
  Philly_Race %>%
  st_transform(crs = 4326)

Philly_White <-
  Philly_Race %>%
  select(WHITE,GEOID)%>%
  dplyr::rename(Count = WHITE)%>%
  st_centroid()%>%
   st_join(.,fishnet)%>%
  group_by(uniqueID) %>%
   dplyr::summarize(CountWhite = sum(Count))

fishnet6 <-
  Philly_White %>%
  st_drop_geometry()%>%
  left_join(.,fishnet)%>%
  st_as_sf()
  
Philly_Black <-
 Philly_Race %>%
  select(BLACK,GEOID)%>%
  rename(Count = BLACK)%>%
  st_centroid()%>%
   st_join(.,fishnet)%>%
  group_by(uniqueID) %>%
  summarize(CountBlack = sum(Count))

fishnet10 <-
  Philly_Black %>%
  st_drop_geometry()%>%
  left_join(.,fishnet)%>%
  st_as_sf()

Philly_Asian <-
  Philly_Race %>%
  select(ASIAN,GEOID)%>%
  rename(Count = ASIAN)%>%
  st_centroid()%>%
   st_join(.,fishnet)%>%
  group_by(uniqueID) %>%
  summarize(CountAsian = sum(Count))

fishnet7 <-
  Philly_Asian %>%
  st_drop_geometry()%>%
  left_join(.,fishnet)%>%
  st_as_sf()

Philly_Total <-
   Philly_Race %>%
  select(TOTAL,GEOID)%>%
  rename(Count = TOTAL)%>%
  st_centroid()%>%
   st_join(.,fishnet)%>%
  group_by(uniqueID) %>%
  summarize(CountTotal = sum(Count))

fishnet8 <-
  Philly_Total %>%
  st_drop_geometry()%>%
  left_join(.,fishnet)%>%
  st_as_sf()


```

```{r crime}

Crime_2020 <- read.csv("Crime_Incidents_2020.csv")

colnamCleaning<-c("the_geom", "cartodb_id", "the_geom_webmercator")
Crime_2020 <-Crime_2020[ , -which(names(Crime_2020) %in% colnamCleaning)]

Crime_2019 <- read.csv("Crime_Incidents_2019.csv")
Crime_2018 <- read.csv("Crime_Incidents_2018.csv")
Crime_2017 <- read.csv("Crime_Incidents_2017.csv")
Crime_2016 <- read.csv("Crime_Incidents_2016.csv")

Crime <-
  rbind(Crime_2020,Crime_2019,Crime_2018, Crime_2017, Crime_2016) %>%na.omit()%>%
   st_as_sf(coords = c("point_x","point_y"),crs = 4326)%>%
  mutate(CrimeCount=1)%>%
  st_join(fishnet)%>%
  group_by(uniqueID)%>%
    summarise(CountCrime = sum(CrimeCount))

fishnet9 <-
  Crime %>%
  st_drop_geometry()%>%
  left_join(.,fishnet)%>%
  st_as_sf()

ggplot()+
  geom_sf(data = Philly_boundary)+
  geom_sf(data = fishnet9, aes(fill = CountCrime))+
  scale_fill_viridis(option = "B", direction = -1)
```
```{r crash fishnet}

Crash_Fish <-
  Crash_Ped %>%
  st_as_sf(coords = c("LONGITUDE","LATITUDE"),crs = 4326) %>%
  mutate(Count = 1)%>%
  st_join(fishnet)%>%
  dplyr::group_by(uniqueID) %>%
  dplyr::summarise(PedCrashCount = sum(Count)) %>%
  st_drop_geometry() %>%
  left_join(fishnet) %>%
  st_as_sf()

```

```{r fishnet join}
library(purrr)

light_net2 <-
  Street_Poles_Lumen %>%
  filter(!LUM_SIZE ==0) %>%
  st_join(.,fishnet)

light_net2 <- light_net2 %>% 
  group_by(uniqueID)%>%
  dplyr::summarise(mean_lumen = sum(LUM_SIZE))

dfs <- list(
  st_drop_geometry(fishnet1), st_drop_geometry(fishnet2), st_drop_geometry(fishnet3), st_drop_geometry(fishnet4), st_drop_geometry(fishnet_5),st_drop_geometry(fishnet6),st_drop_geometry(fishnet7),st_drop_geometry(fishnet8),st_drop_geometry(fishnet9),st_drop_geometry(fishnet10),st_drop_geometry(light_net2), st_drop_geometry(Crash_Fish))
  
  
fishnet_final <-
  purrr::reduce(dfs, dplyr::left_join, by = 'uniqueID')%>%
  right_join(fishnet)%>%
  st_as_sf()

fishnet_final[is.na(fishnet_final)] <- 0

fishnet_final2 <-
  gather(fishnet_final, Variable,value, -geometry,-uniqueID)

vars <- unique(fishnet_final2$Variable)

mapList <- list()
for(i in vars){
  mapList[[i]] <- 
    ggplot() +
      geom_sf(data = filter(fishnet_final2, Variable == i), aes(fill=value), colour=NA) +
      scale_fill_viridis_b(name="") +
      labs(title=i) + theme_map()}

library(grid)
library(gridExtra)

do.call(grid.arrange,c(mapList, ncol=3, top="Variable Counts by Fishnet"))

  
```


```{r}
library(corrplot)
library(ggcorrplot)

fishnet_nu <-
  fishnet_final %>%
  st_drop_geometry()%>%
  select(-uniqueID)

cor(fishnet_nu)%>%
  ggcorrplot(hc.order = TRUE,
           type = "lower",
           outline.color = "white")

fishnet_long <-
  fishnet_final %>%
  st_drop_geometry()%>%
  select(-uniqueID,-CrashCount)%>%
  gather(Variable, value, -PedCrashCount)

fishnet_cor <-
  fishnet_final %>%
  st_drop_geometry()%>%
  dplyr::select(-uniqueID, -CrashCount)%>%
  gather(Variable, value, -PedCrashCount)%>%
  dplyr::group_by(Variable) %>%
  dplyr::summarize(correlation = cor(value, PedCrashCount, use = "complete.obs"))

ggplot(fishnet_long, aes(value, PedCrashCount)) +
  geom_point(size = 0.1) +
  geom_text(data = fishnet_cor, aes(label = paste("r =", round(correlation, 2))),
            x=-Inf, y=Inf, vjust = 1.5, hjust = -.1) +
  geom_smooth(method = "lm", se = FALSE, colour = "black") +
  facet_wrap(~Variable, ncol = 2, scales = "free") +
  labs(title = "Burglary count as a function of risk factors") +
  theme_map()
  


```

